<div id="wrapper">
  
	  <!-- Sidebar -->
	  <div id="sidebar-wrapper">
		<ul class="sidebar-nav">
		  <li class="sidebar-brand"><a href="../index.html">Hi, <?php echo $this->fetchSpecific(0, 'fName')." ".$this->fetchSpecific(0, 'lName'); ?>! Sign out</a></li> 
		  <li><a href="#" data-target="#myModal" data-toggle="modal"><i class="glyphicon glyphicon-user"></i> View profile</a></li>
		  <li><a href="#"><i class="glyphicon glyphicon-th-large"></i> View Matches</a></li>   
		  <li><a href="coordinator.php"><i class="glyphicon glyphicon-briefcase"></i> Job History</a></li>
		</ul>
	  </div>
	  
	  <!-- Modal -->
	<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel">Your Profile</h4>
		  </div>
		  <div class="modal-body">
		
		
		
			  <div class="panel panel-info">
				  <div class="panel-heading">
			  
					  <!-- Coordinators data from CoordinatorsData array -->


					  <h4>Employee ID: <?php echo $this->fetchSpecific(0, 'empID');?></h4>
				  </div>
				  <div class="panel-body">
					  <p><strong>First Name:</strong> <?php echo $this->fetchSpecific(0, 'fName');?></p>
					  <p><strong>Last Name:</strong> <?php echo $this->fetchSpecific(0, 'lName');?></p>
					  <p><strong>User Name:</strong> <?php echo $this->fetchSpecific(0, 'userName');?></p>
				 
				  </div>
				  <div class="panel-footer">
				  </div>
				  <!-- END OF COODINATORS PROFILE -->
			  </div>

		  </div>
		</div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	</div><!-- /.modal -->
	  
	  <!-- Page content -->
	  <div id="page-content-wrapper">
		<div class="content-header">
		  <h1>
			<a id="menu-toggle" href="#" class="btn btn-default"><i class="icon-reorder"></i></a>
			Students:
		  </h1>
		</div>
		<!-- Keep all page content within the page-content inset div! -->
		<div class="page-content inset">
		  <div class="row">
			<div class="col-md-12">
			  <p class="lead">Your Current Students:</p>
			</div>
		
		
			<!-- Lists students under the coodinators guidance -->
		  <?php
		  		$studentList = $this->fetchResults(2);
		  
		  //while($studentList = $this->fetchResults(2))
		 foreach ($studentList as &$item) 
		{
		 echo '<div class="col-md-6">
			  <div class="panel panel-info">
				  <div class="panel-heading">
					  <p><strong>Student ID:</strong> '.$studentList["stuID"].'</p>
					  <p><strong>User Name:</strong> '.$studentList["userName"].'</p>
				  </div>
				  <div class="panel-body">
					  <p><strong>Last Name:</strong> '.$studentList["lName"].'</p>
					  <p><strong>First Name:</strong> '.$studentList["fName"].'</p>
				  
					  <p><strong>Address:</strong> '.$studentList["address"].'</p>
					  <p><strong>E-Mail:</strong> '.$studentList["email"].'</p>
					  <hr>
					  <p><strong>Major:</strong> '.$studentList["major"].'</p>
					  <p><strong>GPA:</strong> '.$studentList["gpa"].'</p>
					  <p><strong>Academic Year:</strong> '.$studentList["academicYear"].'</p>
					  <p><strong>Cohort:</strong> '.$studentList["cohort"].'</p>
					  <p><strong>Credits Completed:</strong> '.$studentList["totalCredits"].'</p>
				  </div>
				  <div class="panel-footer">
					  <button type="button" class="btn btn-success btn-lg btn-block">Select</button>
				  </div>
			  </div>
			</div>';
			}
			?>
		
		

			</div>
		  </div>
		</div>
	  </div>
  
	</div>
